#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from itertools import takewhile

def generateFibonacci():
    n1, n2 = 1, 2
    while True:
        yield n1
        n1, n2 = n2, n1+n2

fibonacci_sequence = generateFibonacci()

fibonaccis = takewhile(lambda n:n < 4000000, fibonacci_sequence)

even_fibonaccis = filter(lambda n: n % 2 == 0, fibonaccis)

print sum(even_fibonaccis)
